debug: .content-collections missing.

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -60,8 +60,8 @@ jobs:
             ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
       - name: Install dependencies
         run: pnpm install --frozen-lockfile
-      - name: Generate content collections
-        run: pnpm content-collections build
+      - name: Check generated content folder
+        run: ls -R .content-collections || echo ".content-collections directory not found or empty"
       - name: Build with Next.js
         run: env && pnpm build --debug
       - name: Upload artifact
